name: property_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # API & Networking
  http: ^1.2.0

  # Database (Neon PostgreSQL)
  postgres: ^3.0.0

  # Local Storage (To stay logged in)
  shared_preferences: ^2.2.2

  # Image Handling for Profile
  image_picker: ^1.2.1

  # Math Utilities
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Recommended for cleaner code

flutter:
  uses-material-design: true

  # Register your local assets here
  assets:
    - assets/images/
    # - assets/icons/

  # If you are using custom fonts like PlusJakartaSans
  # fonts:
  #   - family: PlusJakartaSans
  #     fonts:
  #       - asset: assets/fonts/PlusJakartaSans-Regular.ttf
  #       - asset: assets/fonts/PlusJakartaSans-Bold.ttf
  #         weight: 700